### ISSUE TITLE
Backup no longer working after 2.4

### ISSUE THREAD

**Issue by cciearnold** [bjolivot/ansible-module-fortios#1]
Hi after upgrading to 2.4 the following play doesnt work anymore

- name: Fortinet Devices Backups
  hosts: fortios
  connection: local
  gather_facts: no

  tasks:
    - name: Backup current config
      fortios_config:
        host: "{{ inventory_hostname }}"
        username: "{{ un }}"
        password: "{{ pwd }}"
        backup: yes
        backup_path: /home/arnold/ansible/backups/fortinet

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_KJ0xlZ/ansible_module_fortios_config.py", line 183, in <module>
    main()
  File "/tmp/ansible_KJ0xlZ/ansible_module_fortios_config.py", line 140, in main
    backup(module, f.running_config.to_text())
  File "/tmp/ansible_KJ0xlZ/ansible_modlib.zip/ansible/module_utils/fortios.py", line 84, in backup
TypeError: object of type 'NoneType' has no len()

fatal: [corpfw02]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_KJ0xlZ/ansible_module_fortios_config.py\", line 183, in <module>\n    main()\n  File \"/tmp/ansible_KJ0xlZ/ansible_module_fortios_config.py\", line 140, in main\n    backup(module, f.running_config.to_text())\n  File \"/tmp/ansible_KJ0xlZ/ansible_modlib.zip/ansible/module_utils/fortios.py\", line 84, in backup\nTypeError: object of type 'NoneType' has no len()\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0

**Comment by polaris197** [comment]
Hello, 

I have the same issue.

**Comment by polaris197** [comment]
I found the origin of the problem.
we must set another variable in order to save the configuration :  backup_filename:
I test it,

**Comment by jerhone** [comment]
@polaris197 can you share to us the solution you made for this specific issue? I am using this module for backup but now searching over the net seem frustrating already on my part. Would appreciate if anyone can help on this.

But I will not stop understanding and trying to fix this error I have.

Thanks!

**Comment by jerhone** [comment]
@bjolivot I would like to thank you for maintaining this module. More power to you! God bless!

**Comment by foxpatil** [comment]
Is this issue fixed. ?. I am getting the same error- "Failed while reading configuration backup"}


 Below is my playbook
--------------------

 hosts: all
   connection: local

   tasks:

           - fortios_config:
                   host: "{{ hostname }}"
                   username: "{{ username }}"
                   password: "{{ password }}"
                   vdom: root
                   backup: yes
                   backup_path: /home/netsec/fortinet
                   backup_filename: 002test.cfg


output of the script:
--------
/usr/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature

PLAY [all] *************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [x.x.x.x]

TASK [fortios_config] **************************************************************************************************************************************************
fatal: [x.x.x.x]: FAILED! => **{"**msg": "Failed while reading configuration backup"}****

PLAY RECAP *************************************************************************************************************************************************************
x.x.x.x               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by polaris197** [comment]
I retrieve the solution and I tell you as soon as possible

**Comment by foxpatil** [comment]
> I retrieve the solution and I tell you as soon as possible

That will be a great help @polaris197
